@startuml

left to right direction
rectangle Biblioteca{
usecase "Reservar libro"
usecase "Prestar libro"
usecase "Devolver libro"
usecase "Actualizar catálogo"
}

Socio -- (Reservar libro)
Socio -- (Prestar libro)
(Prestar libro) -- Bibliotecario
Socio -- (Devolver libro)
(Actualizar catálogo) -- Bibliotecario

@enduml